FROM python:3.13.0 AS builder

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


EXPOSE 8000
COPY . .
CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8000"]
